AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Config rule to restrict SSH from 0.0.0.0/0

Resources:

  RestrictedSSHRule:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: org-restricted-ssh
      Description: Checks whether security groups allow SSH access from 0.0.0.0/0
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::SecurityGroup
      Source:
        Owner: AWS
        SourceIdentifier: INCOMING_SSH_DISABLED
